
package com.trade.service.ws.ips;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ScanService", targetNamespace = "http://payat.ips.com.cn/WebService/Scan")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ScanService {


    /**
     * 
     * @param scanPayReq
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://payat.ips.com.cn/WebService/Scan/scanPay")
    @WebResult(name = "scanPayRsp", partName = "scanPayRsp")
    public String scanPay(
            @WebParam(name = "scanPayReq", partName = "scanPayReq")
                    String scanPayReq);

    /**
     * 
     * @param barCodeScanPay
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://payat.ips.com.cn/WebService/Scan/barCodeScanPay")
    @WebResult(name = "barCodeScanPayResult", partName = "barCodeScanPayResult")
    public String barCodeScanPay(
            @WebParam(name = "barCodeScanPay", partName = "barCodeScanPay")
                    String barCodeScanPay);

}
